[build-system]
requires = ["setuptools>=61", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "typify-cli"
version = "0.1.5"
description = "Backend CLI for the Typify inference engine"
readme = "README.md"
license = { file = "LICENSE" }
authors = [
    { name = "Ali Aman", email = "ali.burki1@hotmail.com" }
]
requires-python = ">=3.11"
dependencies = [
    "tantivy",
    "rich",
    "gdown",
    "requests",
]

[project.scripts]
typify = "typify_cli.__main__:main"

[tool.setuptools.packages.find]
where = ["src"]
